/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BoardsRouteImport } from './routes/boards'
import { Route as ClientsRouteImport } from './routes/clients'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BoardsBoardIdRouteImport } from './routes/boards.$boardId'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ClientBoardsBoardIdRouteImport } from './routes/client.boards.$boardId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsRoute = BoardsRouteImport.update({
  id: '/boards',
  path: '/boards',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsRoute = ClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardsBoardIdRoute = BoardsBoardIdRouteImport.update({
  id: '/$boardId',
  path: '/$boardId',
  getParentRoute: () => BoardsRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientBoardsBoardIdRoute = ClientBoardsBoardIdRouteImport.update({
  id: '/client/boards/$boardId',
  path: '/client/boards/$boardId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/clients': typeof ClientsRoute
  '/login': typeof LoginRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/client/boards/$boardId': typeof ClientBoardsBoardIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/clients': typeof ClientsRoute
  '/login': typeof LoginRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/client/boards/$boardId': typeof ClientBoardsBoardIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boards': typeof BoardsRouteWithChildren
  '/clients': typeof ClientsRoute
  '/login': typeof LoginRoute
  '/boards/$boardId': typeof BoardsBoardIdRoute
  '/share/$token': typeof ShareTokenRoute
  '/client/boards/$boardId': typeof ClientBoardsBoardIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boards'
    | '/clients'
    | '/login'
    | '/boards/$boardId'
    | '/share/$token'
    | '/client/boards/$boardId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boards'
    | '/clients'
    | '/login'
    | '/boards/$boardId'
    | '/share/$token'
    | '/client/boards/$boardId'
  id:
    | '__root__'
    | '/'
    | '/boards'
    | '/clients'
    | '/login'
    | '/boards/$boardId'
    | '/share/$token'
    | '/client/boards/$boardId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardsRoute: typeof BoardsRouteWithChildren
  ClientsRoute: typeof ClientsRoute
  LoginRoute: typeof LoginRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ClientBoardsBoardIdRoute: typeof ClientBoardsBoardIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards': {
      id: '/boards'
      path: '/boards'
      fullPath: '/boards'
      preLoaderRoute: typeof BoardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients': {
      id: '/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof ClientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boards/$boardId': {
      id: '/boards/$boardId'
      path: '/$boardId'
      fullPath: '/boards/$boardId'
      preLoaderRoute: typeof BoardsBoardIdRouteImport
      parentRoute: typeof BoardsRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/boards/$boardId': {
      id: '/client/boards/$boardId'
      path: '/client/boards/$boardId'
      fullPath: '/client/boards/$boardId'
      preLoaderRoute: typeof ClientBoardsBoardIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BoardsRouteChildren {
  BoardsBoardIdRoute: typeof BoardsBoardIdRoute
}

const BoardsRouteChildren: BoardsRouteChildren = {
  BoardsBoardIdRoute: BoardsBoardIdRoute,
}

const BoardsRouteWithChildren =
  BoardsRoute._addFileChildren(BoardsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardsRoute: BoardsRouteWithChildren,
  ClientsRoute: ClientsRoute,
  LoginRoute: LoginRoute,
  ShareTokenRoute: ShareTokenRoute,
  ClientBoardsBoardIdRoute: ClientBoardsBoardIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
